#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdg-user-dirs
Version  : 0.15
Release  : 3
URL      : http://user-dirs.freedesktop.org/releases/xdg-user-dirs-0.15.tar.gz
Source0  : http://user-dirs.freedesktop.org/releases/xdg-user-dirs-0.15.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xdg-user-dirs-bin
Requires: xdg-user-dirs-locales
Requires: xdg-user-dirs-doc
Requires: xdg-user-dirs-data
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxslt
BuildRequires : m4
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config-dev
Patch1: 0001-Convert-to-a-stateless-configuration.patch
Patch2: 0002-Include-an-autostart-file-to-ensure-directories-are-.patch

%description
See info at:
http://freedesktop.org/wiki/Software/xdg-user-dirs

%package bin
Summary: bin components for the xdg-user-dirs package.
Group: Binaries
Requires: xdg-user-dirs-data

%description bin
bin components for the xdg-user-dirs package.


%package data
Summary: data components for the xdg-user-dirs package.
Group: Data

%description data
data components for the xdg-user-dirs package.


%package doc
Summary: doc components for the xdg-user-dirs package.
Group: Documentation

%description doc
doc components for the xdg-user-dirs package.


%package locales
Summary: locales components for the xdg-user-dirs package.
Group: Default

%description locales
locales components for the xdg-user-dirs package.


%prep
%setup -q -n xdg-user-dirs-0.15
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1492800211
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492800211
rm -rf %{buildroot}
%make_install
%find_lang xdg-user-dirs

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdg-user-dir
/usr/bin/xdg-user-dirs-update

%files data
%defattr(-,root,root,-)
/usr/share/xdg/autostart/xdg-user-dirs.desktop
/usr/share/xdg/user-dirs.conf
/usr/share/xdg/user-dirs.defaults

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*

%files locales -f xdg-user-dirs.lang
%defattr(-,root,root,-)

