#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdg-user-dirs
Version  : 0.15
Release  : 1
URL      : http://user-dirs.freedesktop.org/releases/xdg-user-dirs-0.15.tar.gz
Source0  : http://user-dirs.freedesktop.org/releases/xdg-user-dirs-0.15.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xdg-user-dirs-bin
Requires: xdg-user-dirs-locales
Requires: xdg-user-dirs-doc
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : libxslt
BuildRequires : perl(XML::Parser)

%description
See info at:
http://freedesktop.org/wiki/Software/xdg-user-dirs

%package bin
Summary: bin components for the xdg-user-dirs package.
Group: Binaries

%description bin
bin components for the xdg-user-dirs package.


%package doc
Summary: doc components for the xdg-user-dirs package.
Group: Documentation

%description doc
doc components for the xdg-user-dirs package.


%package locales
Summary: locales components for the xdg-user-dirs package.
Group: Default

%description locales
locales components for the xdg-user-dirs package.


%prep
%setup -q -n xdg-user-dirs-0.15

%build
export LANG=C
export SOURCE_DATE_EPOCH=1483046338
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang xdg-user-dirs

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xdg-user-dir
/usr/bin/xdg-user-dirs-update

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*

%files locales -f xdg-user-dirs.lang
%defattr(-,root,root,-)

